Add some words about the Apache community
eufossa/apache-hackathon-2019 pull request #6
Opened 2019-05-05 08:18 UTC by NiklasMerz

I am looking how Apache works from the outside for some time. At the hackathon I got the chance  to talk to some of the Apache commiters.

2019-05-05 11:03 UTC, jfhovinne requested changes
Thanks @NiklasMerz !
Minor typos.

2019-05-05 11:03 UTC, jfhovinne commented on README.md
> +[Observations on the Apache community](theapacheway.md)
Maybe a list here ?

2019-05-05 11:03 UTC, jfhovinne commented on theapacheway.md
> +The second FOSS Hackathon by EU FOSSA 2 was a good opportinity for outside observers to get a sense of how Open Source works "The Apache Way".
"opportunity"

2019-05-05 11:03 UTC, jfhovinne commented on theapacheway.md
> +The Apache Way is all about community. Decission are made together and take place in public. It can be hard to understand to understand how and why Open Source and Apache works from the outside. When
"Decisions" are ...
"to understand" (repeated)
"how and why Open Source and Apache work"
"get a feeling of why"

2019-05-05 11:03 UTC, jfhovinne commented on theapacheway.md
> +Many Apache Project Management Committee members from different projects were part of the event and showed attendees not part of any Apache community how projects are working at the Apache Software F
Apache Software Foundation

2019-05-05 11:53 UTC, NiklasMerz commented
Thank you for spotting these mistakes. I fixed them and added some words.

2019-05-06 05:55 UTC, jfhovinne approved these changes
Nice work, thanks @NiklasMerz

2019-05-06 05:55 UTC, merged